name: CI
on:
  push:
    branches: 
      - '*'
    tags:
      - '!*'
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        sudo xcode-select --switch /Applications/Xcode_12_beta.app
        xcrun xcodebuild -version
        ./ci.sh
