name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Test
      run: |
        sudo xcode-select --switch /Applications/Xcode_11.app
        xcrun xcodebuild -version
        ./ci.sh
